FROM node:14.4.0-alpine
WORKDIR ${HOME}
COPY . .

ARG FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_URL
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_STRAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDER_ID
ARG FIREBASE_APP_ID
ARG FIREBASE_MEASUREMENT_ID
ARG LIFF_ID

ENV HOST 0.0.0.0

RUN yarn install && yarn run build

EXPOSE ${CONTAINER_PORT}